--- 
- 
  connection: local
  gather_facts: false
  hosts: apic
  name: "ENSURE APPLICATION CONFIGURATION EXISTS"
  tasks: 
    - 
      aci_domain: 
        domain: MyvCenter
        domain_type: vmm
        host: "{{ ansible_host }}"
        password: "{{ password }}"
        state: present
        username: "{{ username }}"
        validate_certs: false
        vm_provider: vmware
      name: "Add a new vmm domain"
    - 
      aci_epg_to_domain: 
        ap: intranet
        domain: MyvCenter
        domain_type: vmm
        epg: web
        host: "{{ ansible_host }}"
        password: "{{ password }}"
        state: present
        tenant: SIRIUS
        username: "{{ username }}"
        validate_certs: false
        vm_provider: vmware
      name: "Add a domain to EPG binding (vmm)"
    - 
      aci_rest: 
        content: 
          vmmProvP: 
            ? "-vendor"
            : VMware
            vmmDomP: 
              ? "-accessMode"
              : read-write
              ? "-name"
              : MyvCenter
              infraRsVlanNs: 
                ? "-tDn"
                : "uni/infra/vlanns-[dCloud_VLAN_Pool]-dynamic"
              vmmUsrAccP: 
                ? "-name"
                : defaultAccP
                ? "-pwd"
                : "'C1sco12345!'"
                ? "-usr"
                : administrator@vsphere.local
        host: "{{ ansible_host }}"
        method: post
        password: "{{ password }}"
        path: /api/node/mo/.json
        username: "{{ username }}"
        validate_certs: false
      delegate_to: localhost
      name: "Add credentials to VMM"
  vars_prompt: 
    - 
      name: tenant
      private: false
      prompt: "What would you like to name your Tenant?"
