---
- name: USE ACI REST MODULE
  hosts: apic
  connection: local
  gather_facts: False


  tasks:
    - name: CREATE DN
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        method: "post"
        path: "api/node/mo/uni/infra.json"
        content: '{\"infraInfra\":{\"attributes\":{\"dn\":\"uni/infra\",\"status\":\"created,modified\"},\"children\":[]}}'

#  tasks:
#    - name: CREATE VMM DOMAIN
#      aci_rest:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        validate_certs: False
#        method: "post"
#        path: "api/node/mo/uni/vmmp-VMware/dom-My-vCenter.json"
#        content: '{"vmmDomP":{"attributes":{"dn":"uni/vmmp-VMware/dom-My-vCenter","name":"My-vCenter","rn":"dom-My-vCenter","status":"created"},"children":[{"infraRsVlanNs":{"attributes":{"tDn":"uni/infra/vlanns-[dCloud_VLAN_Pool]-dynamic","status":"created"},"children":[]}},{"vmmVSwitchPolicyCont":{"attributes":{"dn":"uni/vmmp-VMware/dom-My-vCenter/vswitchpolcont","status":"created,modified"},"children":[]}}]}}'


#  tasks:
#    - name: CREATE VCENTER CONNECTION
#      aci_rest:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        validate_certs: False
#        method: "post"
#        path: "api/node/mo/uni/infra/attentp-default.json"
#        content: '{"infraRsDomP":{"attributes":{"tDn":"uni/vmmp-VMware/dom-My-vCenter","status":"created,modified"},"children":[]}}'


#  tasks:
#    - name: CREATE VCENTER USER ACCOUNT
#      aci_rest:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        validate_certs: False
#        method: "post"
#        path: "api/node/mo/uni/vmmp-VMware/dom-My-vCenter/usracc-defaultAccP.json"
#        content: '{"vmmUsrAccP":{"attributes":{"dn":"uni/vmmp-VMware/dom-My-vCenter/usracc-defaultAccP","name":"defaultAccP","usr":"administrator@vsphere.local","pwd":"C1sco12345!","rn":"usracc-defaultAccP","status":"created"},"children":[]}}'


  tasks:
    - name: LINK VMM TO VCENTER
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        method: "post"
        path: "api/node/mo/uni/vmmp-VMware/dom-My-vCenter/ctrlr-dCloud-DC.json"
        content: '{"vmmCtrlrP":{"attributes":{"dn":"uni/vmmp-VMware/dom-My-vCenter/ctrlr-dCloud-DC","name":"dCloud-DC","hostOrIp":"198.18.133.30","rootContName":"dCloud-DC","rn":"ctrlr-dCloud-DC","status":"created"},"children":[{"vmmRsAcc":{"attributes":{"tDn":"uni/vmmp-VMware/dom-My-vCenter/usracc-defaultAccP","status":"created"},"children":[]}}]}}'

