---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "tenant"
      prompt: "What would you like to name your Tenant?"
      private: no

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_epg_to_domain:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        ap: "intranet"
        epg: "sql"
        domain: "My-vCenter"
        domain_type: "vmm"
        validate_certs: "no"
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
